services:
  - type: web
    name: bun
    env: docker
    repo: https://github.com/whenparty/gpt-telegram-bot-task-processor
    plan: starter
    autoDeploy: false
    envVars:
      - key: BUN_VERSION
        value: 1.1.0=
    buildCommand: bun install
    startCommand: bun start
