name: Deploy

on:
  workflow_call:
    secrets:
      ANTHROPIC_API_KEY:
        required: true
      OPENAI_API_KEY:
        required: true
      POSTGRES_URL:
        required: true
      TELEGRAM_BOT_API_TOKEN:
        required: true
      RENDER_SERVICE_ID:
        required: true
      RENDER_API_KEY:
        required: true

jobs:
  deploy-to-render:
    runs-on: ubuntu-latest
    env:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
      TELEGRAM_BOT_API_TOKEN: ${{ secrets.TELEGRAM_BOT_API_TOKEN }}
      POSTGRES_URL: ${{secrets.POSTGRES_URL}}
    steps:
      - name: Check out branch main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Apply database migrations
        uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run db:migrate

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
